### ISSUE TITLE
Error in BCC library

### ISSUE THREAD

**Issue by maltamiranda** [Santandersecurityresearch/CryptoMon#22]
Hi,

I have been trying test the tool but Im having issues when running it. I have followed the guide and tried with different "jammy" versions (22.04 and 22.04.05) but without success as its showing error when using the **BPF** library in the **bpf.py** (I think specifically when doing the _#include <linux/bpf.h>_.

The only pending thing from the requirements is the _bbc==0.21.0_ since that version is not listed by the official ubuntu repositories. 
I have tried building different bcc versions from https://github.com/iovisor/bcc/blob/python3-testing/INSTALL.md#ubuntu---binary but without success. Is ther a correct way to install the bcc for the tool to run?

Thanks for your support.

Please see below the error log.

```root@matias-VirtualBox:/home/matias/CryptoMon# python3 cryptomon.py
Available network interfaces:
1: lo
2: enp0s3
Select an interface by number: 2
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:148:
include/linux/compiler-clang.h:45:9: warning: '_HAVE_BUILTIN_BSWAP32_' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
<command line>:4:9: note: previous definition is here
#define _HAVE_BUILTIN_BSWAP32__ 1
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:148:
include/linux/compiler-clang.h:46:9: warning: '_HAVE_BUILTIN_BSWAP64_' macro redefined [-Wmacro-redefined]
#define _HAVE_BUILTIN_BSWAP64__
<command line>:5:9: note: previous definition is here
#define _HAVE_BUILTIN_BSWAP64__ 1
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:148:
include/linux/compiler-clang.h:47:9: warning: '_HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
In file included from /virtual/main.c:5:
include/linux/bpf.h:340:10: еггог: invalid application of 'sizeof' to an incomplete type 'struct bpf_timer' 
	return sizeof(struct bpf_timer);
include/linux/bpf.h:340:24: note: forward declaration of 'struct bpf_timer' 
	return sizeof(struct bpf_timeг);
include/linux/bpf.h:346:10: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_list_head' 
	return sizeof(struct bpf_list_head);
include/linux/bpf.h:346:24: note: forward declaration of 'struct bpf_list_head' 
	return sizeof(struct bpf_list_head);
include/linux/bpf.h:348:10: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_list_node' 
	return sizeof(struct bpf_list_node);
include/linux/bpf.h:348:24: note: forward declaration of 'struct bpf_list_node' 
	return sizeof(struct bpf_list_node);
include/linux/bpf.h:350:10: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_rb_root' 
	return sizeof(struct bpf_rb_root);
include/linux/bpf.h:350:24: note: forward declaration of 'struct bpf_rb_root' 
	return sizeof(struct bpf_rb_root);
include/linux/bpf.h:352:10: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_rb_node' 
	return sizeof(struct bpf_rb_node);
include/linux/bpf.h:352:24: note: forward declaration of 'struct bpf_rb_node' 
	return sizeof(struct bpf_rb_node);
include/linux/bpf.h:354:10: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_refcount' 
	return sizeof(struct bpf_refcount);
include/linux/bpf.h:354:24: note: forward declaration of 'struct bpf_refcount' 
	return sizeof(struct bpf_refcount);
include/linux/bpf.h:367:10: error: invalid application of '_alignof' to an incomplete type 'struct bpf_timer' 
	return __alignof__(struct bpf_timer);
include/linux/bpf.h:367:29: note: forward declaration of 'struct bpf_timer' 
	return _alignof__(struct bpf_timeг);
include/linux/bpf.h:373:10: error: invalid application of '_alignof' to an incomplete type 'struct bpf_list_head' 
	return _alignof__(struct bpf_list_head);
include/linux/bpf.h:373:29: note: forward declaration of 'struct bpf_list_head' 
	return __alignof__(struct bpf_list_head);
include/linux/bpf.h:375:10: error: invalid application of '_alignof' to an incomplete type 'struct bpf_list_node' 
	return __alignof__(struct bpf_list_node);
include/linux/bpf.h:375:29: note: forward declaration of 'struct bpf_list_node'
	return _alignof__(struct bpf_list_node);
include/linux/bpf.h:377:10: еггог: invalid application of '_alignof' to an incomplete type 'struct bpf_rb_root'
	return __alignof__(struct bpf_rb_root);
include/linux/bpf.h:377:29: note: forward declaration of 'struct bpf_rb_root' 
	return __alignof__(struct bpf_rb_root);
include/linux/bpf.h:379:10: еггог: invalid application of '_alignof' to an incomplete type 'struct bpf_rb_node'
	return ___alignof__(struct bpf_rb_node);
include/linux/bpf.h:379:29: note: forward declaration of 'struct bpf_rb_node'
	return __alignof__(struct bpf_rb_node);
include/linux/bpf.h:381:10: error: invalid application of '_alignof' to an incomplete type 'struct bpf_refcount'
	return _alignof__(struct bpf_refcount);
include/linux/bpf.h:381:29: note: forward declaration of 'struct bpf_refcount'
	return __alignof__(struct bpf_refcount);
include/linux/bpf.h:931:50: error: use of undeclared identifier 'BPF_PSEUDO_FUNC'
	return bpf_is_ldimm64(insn) && insn->src_reg == BPF_PSEUDO_FUNC;
include/linux/bpf.h:2289:30: error: field has incomplete type 'enum bpf_cgroup_iter_order' 
    enum bpf_cgroup_iter_order order;
include/linux/bpf.h:2289:8: note: forward declaration of 'enum bpf_cgroup_iter_order' 
    enum bpf_cgroup_iter_order order;
include/linux/bpf.h:2516:59: warning: declaration of 'struct bpf_core_relo' will not be visible outside of this function [-Wvisibility]
int bpf_core_apply(struct bpf_core_ctx *ctx, const struct bpf_core_relo *relo,
4 warnings and 14 errors generated.
Traceback (most recent call last):
File "/home/matias/CryptoMon/cryptomon.py", line 78, in <module>
cm = CryptoMon(iface=args.interface, File "/home/matias/CryptoMon/cryptomon/__init__.py", line 43, in __init__
self.b = BPF(text=bpf_code)
File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 364, in __init__ raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
root@matias-VirtualBox:/home/matias/CryptoMon#
```

**Comment by unprovable** [comment]
Hello! 

sorry for the delay - lemme see if I can replicate and then see what the fix might be :) Thanks for your patience, M.

**Comment by maltamiranda** [comment]
Hi @unprovable thanks for update. I have just test it in a fresh VM and I'm still the same error. 
Let me try to give as much information as possible for you to replicate it.

- Virtual Box Versión 7.0.14 r161095 (Qt5.15.2)
- ubuntu-22.04.5-desktop-amd64

Once installed I ran the following command

```
matias@matias-VirtualBox:~/CryptoMon$ history
    1  sudo apt update
    2  sudo apt install build-essential dkms linux-headers-$(uname -r)
    3  sudo mount /dev/cdrom /mnt
    4  sudo /mnt/VBoxLinuxAdditions.run #VBox tools
    5  sudo reboot
    6  sudo apt install git
    7  git clone https://github.com/Santandersecurityresearch/CryptoMon.git
    8  cd CryptoMon/
    9  chmod +x ubuntu-setup.sh 
   10  sudo ./ubuntu-setup.sh 
   11  mongosh # and do the mentioned configuration in mongo
```
 After that, given that everything was installed with sudo I tried to run it with root (otherwise with sudo cant use the export of the variables)

```
root@matias-VirtualBox:/home/matias/CryptoMon# history
    1  export DB_URL="mongodb://cryptomonUser:<password>@<uri>:27017/cryptomon?retryWrites=true&w=majority"
    2  export DB_NAME="cryptomon"
    3  python3 cryptomon.py -i enp0s3 &
```

and Im getting again the same error with the BPF module.

Also in order to run it with the normal user I modified the fapi config file __init__.py

```
class DatabaseSettings(BaseSettings):
    DB_URL: str = "mongodb://cryptomonUser:<password>@<uri>:27017/cryptomon?retryWrites=true&w=majority"
    DB_NAME: str = "cryptomon"
```

and run it with the normal user

```
matias@matias-VirtualBox:~/CryptoMon$ history"
   17  sudo python3 cryptomon.py
```

but still the same error. Could the error be related to running the program in a VM?

Regards,
Mati

**Comment by unprovable** [comment]
I'm using a VM as well, albeit on UTM on a Mac (which is QEMU based, so it shouldn't really change much in this instance). 

I'll try with the precise Ubuntu version you're using here and see if I can replicate. If not, I'll try to get you some things to check. 

Cheers, M.

**Comment by unprovable** [comment]
PS - I'm using `ubuntu-24.04.1-live-server-arm64` - is there a way you could try using this? ARM64 or AMD64 both work when I've tested them. M.

**Comment by maltamiranda** [comment]
Hi Mark,

I was able to make it work but in my case with **ubuntu-24.04.1-live-server-amd64**. Still would like to leave some comments on the things I had to do in order to make it work.

- with the last update PEP 668 now the python libraries has to be installed with venv, so the ubuntu-setup.sh shows error at the end
- update the documentation the part of mongosh, if its executed like that it creates the account in the test collection instead of the cryptomon. Just need to run "use cryptomon" before creating the accounts so its created in the correct collection
- (not necessary) In my case to make use of the way bcc is installed I have to copy the installed version to my venv used 
```
sudo cp -r /usr/lib/python3/dist-packages/bcc /root/<venv>/lib/python3.12/site-packages/
sudo cp -r /usr/lib/python3/dist-packages/bcc-0.29.1.egg-info /root/<venv>/lib/python3.12/site-packages/
```
- With that pydantic version I have to change fapi/app/models.py
```
#from pydantic_settings import BaseModel, Field
from pydantic import BaseModel, Field
```
- The requirements.txt I have to run it differently due to the dependencies of the libraries not being compatible
```
pip install pymongo==4.8.0 fastapi==0.111.1 jc==1.25.3 motor==3.5.1  tinydb==4.8.0 uvicorn==0.30.0 psutil==6.0.0  scapy==2.5.0
pip install pydantic==1.10.18
pip install pydantic_settings==2.4.0
```
- Also used this pcap sample https://github.com/mmguero-dev/Malcolm-PCAP/raw/refs/heads/main/pcaps/protocols/SSL.pcap and got quite a few errors but couldnt debug them yet.

**Comment by unprovable** [comment]
Glad you got it working! For the errors, please raise a bug issue if you
can. For the rest, please raise a PR! Thanks! M.
